- name: install the latest packages for firewalld
  package:
    name: firewalld
    state: present

- name: Enable and unmask the firewalld
  systemd:
    name: "firewalld.service"
    daemon_reload: yes
    state: started
    masked: no
    enabled: yes

- name: Open firewall for service ssh
  firewalld:
    service: "{{ items }}"
    permanent: yes
    state: enabled
  loop:
    - ssh