---

- name: Open ports
  import_role:
    name: os/firewalld
  vars:
    firewall_ports: "80/tcp"

- name: Allow selinux
  import_role:
    name: os/selinux
  vars:
    selinux_files: "'/srv/www(/.*)?'"

- name: Configure nginx
  block:
    - name: update nginx config
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
      notify:
        - reload nginx

#    - name: update upstream config
#      template:
#        src: load-balancer.conf
#        dest: /etc/nginx/conf.d/load-balancer.conf
#        owner: root
#      notify:
#        - reload nginx
