---

- name: create letsencrypt certificate directory
  file:
    path: '/srv/www'
    state: directory

- name: Firewall role
  include_role:
    name: os/firewalld
  loop:
    - '80/tcp'
    - '443/tcp'
  loop_control:
    loop_var: firewall_ports

- name: Allow selinux
  include_role:
    name: os/selinux
  vars:
    selinux_files: "/srv/www(/.*)?"

- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  community.crypto.openssl_dhparam:
    path: /etc/ssl/dhparams.pem

- name: Configure nginx
  block:
    - name: update nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
      notify:
        - reload nginx

    - name: update nginx statics
      copy:
        src: "files/"
        dest: "/srv/www/site"
        owner: nginx
      notify:
        - reload nginx

#    - name: update upstream config
#      template:
#        src: load-balancer.conf
#        dest: /etc/nginx/conf.d/load-balancer.conf
#        owner: root
#      notify:
#        - reload nginx
