---

- name: create logrotate configuration file
  template:
    src: logrotate.conf.j2
    dest: "{{ logrotate_path_file }}"
    owner: root
    group: root
    mode: 0644

- name: create logrotate for syslog
  template:
    src: syslog.logrotate.j2
    dest: "{{ logrotate_include_dir }}/syslog"
    owner: root
    group: root
    mode: 0644

- name: Copy /etc/cron.hourly/logrotate file
  template:
    src: logrotate.cron.hourly.j2
    dest: /etc/cron.hourly/logrotate
    owner: root
    group: root
    mode: 0700
